server:
  port: 8925
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8460/eureka

spring:
  application:
    name: ZASGateway
  redis:
    host: 47.93.49.119  #配置redis的主机地址，需要修改成自己的
    database: 5
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 50 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool 的状态为exhausted(耗尽)
        max-idle: 20 # 连接池中的最大空闲连接，默认值是8。
        min-idle: 5  # 连接池中的最小空闲连接，默认值是0。
        # max-wait: 5 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接 抛出JedisConnectionException

#zuul:
#  routes:
#    eureka_client:
#      path: /eureka_client/**
#      serviceId: EurekaClient

management:
  endpoints:
    web:
      exposure:
        include: env,refresh